# Generated by Django 2.1.1 on 2018-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bggId', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
