# Generated by Django 2.1.1 on 2019-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_gameplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='HNStory',
            fields=[
                ('storyJSON', models.TextField()),
                ('hnUserId', models.IntegerField()),
                ('hnStoryId', models.IntegerField(primary_key=True, unique=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopStoryIdsByTime',
            fields=[
                ('storyIds', models.TextField()),
                ('topTime', models.DateTimeField(unique=True, primary_key=True, auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HNTopStory',
            fields=[
                ('hnStoryId', models.IntegerField(unique=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('story', models.TextField()),
                ('marked_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
